### ISSUE TITLE
Hi, Back Button Problem

### ISSUE THREAD

**Issue by Metallicali** [collinph/jl-coloringbook#1]
Hi, Undoing the operation turns all drawings into one color :( help me?

![1](https://user-images.githubusercontent.com/10944698/122879891-134c4580-d342-11eb-91c0-d4780d8f8699.jpg)
![2](https://user-images.githubusercontent.com/10944698/122879896-15160900-d342-11eb-84a3-eaba0f1e798a.jpg)

**Comment by collinph** [comment]
Thank you for pointing out this issue. I'm looking into it now.

**Comment by collinph** [comment]
I just fixed the problem in the .js file.. I'll push it out to the CDN, Thank you for reporting the issue!

**Comment by collinph** [comment]
Fully pushed out and released. Please retry and verify that it is working for you. You may need to hard refresh your browser if you're using the CDN or demo

**Comment by Metallicali** [comment]
Error fixed, thank you very much 😊

**Comment by collinph** [comment]
Glad it worked for you, please let me know if you have other requests or bug reports.

**Comment by Metallicali** [comment]
Has a problem painting small areas. Solution zoom button for desktop computer. 

I have a problem with height when zooming in. Otherwise I would have shared. I guess I failed, but that's the problem. Thank you for your interest.
![1](https://user-images.githubusercontent.com/10944698/123504013-499a0580-d65f-11eb-81c1-54659d0730e5.jpg)
![2](https://user-images.githubusercontent.com/10944698/123504025-66363d80-d65f-11eb-96be-8ee08b4bb5db.jpg)
